### ISSUE TITLE
Release 0.3.15

### ISSUE THREAD

**Issue by eed3si9n** [typesafehub/zinc#110]

**Comment by eed3si9n** [comment]
oops. Forgot about your PR, but I did release 0.3.15 just now.

**Comment by gslowikowski** [comment]
You didn't push changes and a tag.

**Comment by eed3si9n** [comment]
Yea. I just merged https://github.com/typesafehub/zinc/pull/111 and tagged https://github.com/typesafehub/zinc/releases/tag/v0.3.15
