### ISSUE TITLE
I can't change zinc default compiler version (scala version 2.10.4) to my projects scala version 2.11.8

### ISSUE THREAD

**Issue by Tyriod** [typesafehub/zinc#114]
I am trying to build an open source app which uses scala version 2.11.8 (ie wire-android). I tried to compile it, it worked but has some problems like the video not working well so when i used terminal to build it with the gradle code = ./gradlew assembleProdRelease --info, I found out that the scala part of the app is compiling with 2.10.4 instead of 2.11.8. I tried all solutions online but it would say zinc not found.... Please any solution to this?

**Comment by SethTisue** [comment]
how exactly would I reproduce the problem on my own computer?

**Comment by Tyriod** [comment]
download wire-android open source at https://github.com/wireapp/wire-android then import it after its through, build the project with terminal using ./gradlew assembleProdRelease --info and then discover what happens when it wants to compile scala. Note: IDE Android Studio

**Comment by SethTisue** [comment]
do you have reason to believe this stems from a bug in zinc and not just a mistake in that particular projects's particular build configuration...? (did you consider opening the issue at https://github.com/wireapp/wire-android/issues and seeing whether that project's maintainers agree that the underlying cause is a bug in zinc...?)

**Comment by SethTisue** [comment]
> I found out that the scala part of the app is compiling with 2.10.4 instead of 2.11.8

what is your evidence of that...?

**Comment by Tyriod** [comment]
When I compile the source with ./gradlew assembleProdRelease --info I discovered that when zinc compiler shows up its version is 0.3.7 and Scala version is 2.10.4. I was just trying to find out if there is any workaround to help me fix this Thank You.

**Comment by SethTisue** [comment]
I would suggest you take it up at https://github.com/wireapp/wire-android/issues

**Comment by Tyriod** [comment]
Thanks
