### ISSUE TITLE
Cannot start zinc 0.3.0

### ISSUE THREAD

**Issue by adamretter** [typesafehub/zinc#46]
I have happily been using Zinc 0.3.0 on CentOS 6.5, but today when I come to start up zinc by running `/opt/zinc/bin/zinc -start` I get the following error:

`Unexpected chunk type 47 ('/')`

The error code returned is `229`.

I removed zinc and re-installed it, but the error persists. Any ideas?

**Comment by tedyu** [comment]
```
zinc-0.3.9/bin/zinc -start -port 3030
Unexpected chunk type 108 ('l')
```
There was no corresponding directory under ~/.zinc :
```
ls ~/.zinc
0.3.5
```
2.6.32-504.el6.x86_64 #1 SMP Wed Oct 15 04:27:16 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

What can I do next ?

Thanks

**Comment by vijayk** [comment]
@tedyu 

We had similar issue as reported by you above and found that the default port # 3030 is pre-occupied.

$ netstat -plten| grep 3030

If it returns any value. You would need to kill the service running not he port 3030 before starting zinc service.
