### ISSUE TITLE
Cross-publish Zinc for 2.10 & 2.11

### ISSUE THREAD

**Issue by pdalpra** [typesafehub/zinc#63]
Could it be possible to cross-publish Zinc for 2.10 & 2.11.
Our use case is that we bundle and use Zinc for compiling Scala classes, but since Zinc depends itself on Scala 2.10, we're "locked" to Scala 2.10 or we would end up with multiple scala-library for different Scala versions in the classpath, which would most certainly make a mess...

**Comment by gkossakowski** [comment]
Is this still an issue for you?

**Comment by pdalpra** [comment]
It is not, I found an alternative.
