### ISSUE TITLE
Zinc 0.3.7 doesn't compile Java under JDK 1.8.0

### ISSUE THREAD

**Issue by jdevelop** [typesafehub/zinc#82]
with **JDK6**:

    java -version
    java version "1.6.0_45"
    Java(TM) SE Runtime Environment (build 1.6.0_45-b06)
    Java HotSpot(TM) 64-Bit Server VM (build 20.45-b01, mixed mode)

Zinc is configured by Maven as:

    zinc -status
    Nailgun server running with 1 cached compiler

    Version = 0.3.7

    Zinc compiler cache limit = 5
    Resident scalac cache limit = 0
    Analysis cache limit = 5

    Compiler(Scala 2.11.5) [7e768ee6]
    Setup = {
       scala compiler = /home/bofh/.m2/repository/org/scala-lang/scala-compiler/2.11.5/scala-compiler-2.11.5.jar
       scala library = /home/bofh/.m2/repository/org/scala-lang/scala-library/2.11.5/scala-library-2.11.5.jar
       scala extra = {
          /home/bofh/.m2/repository/org/scala-lang/modules/scala-parser-combinators_2.11/1.0.3/scala-parser-combinators_2.11-1.0.3.jar
          /home/bofh/.m2/repository/org/scala-lang/scala-library/2.11.4/scala-library-2.11.4.jar
          /home/bofh/.m2/repository/org/scala-lang/scala-library/2.11.2/scala-library-2.11.2.jar
          /home/bofh/.m2/repository/org/scala-lang/modules/scala-xml_2.11/1.0.3/scala-xml_2.11-1.0.3.jar
          /home/bofh/.m2/repository/org/scala-lang/scala-reflect/2.11.5/scala-reflect-2.11.5.jar
          /home/bofh/java/zinc-0.3.7/lib/scala-reflect.jar
       }
       sbt interface = /home/bofh/java/zinc-0.3.7/lib/sbt-interface.jar
       compiler interface sources = /home/bofh/java/zinc-0.3.7/lib/compiler-interface-sources.jar
       java home = 
       fork java = false
       cache directory = /home/bofh/.zinc/0.3.7
    }

compilation works just fine. 

With **JDK8**

    java -version                                         
    java version "1.8.0_45"
    Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
    Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

it fails:

    incompatible types: Object cannot be converted to Tween
    [error]                     for (Tween tween : ImmutableList.copyOf(parentLayer.findTweenListForTween(SwitcherTween.NAME))){

Zinc status

    Version = 0.3.7

    Zinc compiler cache limit = 5
    Resident scalac cache limit = 0
    Analysis cache limit = 5

    Compiler(Scala 2.11.5) [9a5e228]
    Setup = {
       scala compiler = /home/bofh/.m2/repository/org/scala-lang/scala-compiler/2.11.5/scala-compiler-2.11.5.jar
       scala library = /home/bofh/.m2/repository/org/scala-lang/scala-library/2.11.5/scala-library-2.11.5.jar
       scala extra = {
          /home/bofh/.m2/repository/org/scala-lang/modules/scala-parser-combinators_2.11/1.0.3/scala-parser-combinators_2.11-1.0.3.jar
          /home/bofh/.m2/repository/org/scala-lang/scala-library/2.11.2/scala-library-2.11.2.jar
          /home/bofh/.m2/repository/org/scala-lang/modules/scala-xml_2.11/1.0.3/scala-xml_2.11-1.0.3.jar
          /home/bofh/.m2/repository/org/scala-lang/scala-reflect/2.11.5/scala-reflect-2.11.5.jar
          /home/bofh/.m2/repository/org/scala-lang/scala-library/2.11.4/scala-library-2.11.4.jar
          /home/bofh/java/zinc-0.3.7/lib/scala-reflect.jar
       }
       sbt interface = /home/bofh/java/zinc-0.3.7/lib/sbt-interface.jar
       compiler interface sources = /home/bofh/java/zinc-0.3.7/lib/compiler-interface-sources.jar
       java home = 
       fork java = false
       cache directory = /home/bofh/.zinc/0.3.7
    }

without incremental compilation and Zinc  - everythig compiles just fine.

Any idea why is that and how Java versio may affect the compilation?

**Comment by jsuereth** [comment]
Right now, We only compile zinc against JDK6 to ensure maximum compatibility.  However, we should be able to run zinc on a JDK8.

**Comment by jdevelop** [comment]
It does run under JDK8, but it fails with some weird errors if trying to compile somthing.

**Comment by garysieling** [comment]
I experienced something similar to this (slightly different type checking error, and running Zinc using gradle), and the fix ended up being upgrading the JDK referenced in JAVA_HOME from 1.8.0_25 to 1.8.0_60. You might want check JAVA_HOME in addition to java -version, because depending how you're running it the one from your path might be ignored.

See here for what I did:
https://www.garysieling.com/blog/fixing-scala-type-errors-in-gradle-incompatible-types-inference-variable-e-has-incompatible-bounds-cannot-infer-type-variable

**Comment by eed3si9n** [comment]
Assuming that JDK 8 bump is going to fix, I'm going to close this for now.
