### ISSUE TITLE
Update sbt version to 0.13.11

### ISSUE THREAD

**Issue by ijuma** [typesafehub/zinc#99]
There are a number of incremental compiler improvements in 0.13.11 and it would be good for zinc to benefit from those too.

I tried bumping the version myself, but it failed to resolve dependencies:

```
sbt.ResolveException: unresolved dependency: com.typesafe.sbt#incremental-compiler;0.13.11: not found
unresolved dependency: com.typesafe.sbt#compiler-interface;0.13.11: not found
```

**Comment by cvogt** [comment]
+1

**Comment by cvogt** [comment]
please @eed3si9n :D

**Comment by paulp** [comment]
@cvogt So I guess this repo is abandonware, and it's https://github.com/sbt/zinc or bust? But this issue is easy to fix so it'd be nice if you could publish up-to-date artifacts for this before smothering it for good. I sent a PR, #101.

**Comment by eed3si9n** [comment]
Thanks for the PR. I'll into this now. I merged #102 to update Travis file.

**Comment by eed3si9n** [comment]
Zinc 0.13.11 is now available - http://downloads.typesafe.com/zinc/0.3.11/zinc-0.3.11.tgz

**Comment by cvogt** [comment]
thx guys!
